HubSpot/NioImapClient

pom.xml, src/main/java/com/hubspot/imap/ImapClientFactory.java, src/main/java/com/hubspot/imap/client/ImapClient.java, src/test/java/com/hubspot/imap/BaseGreenMailServerTest.java, src/test/java/com/hubspot/imap/ConcurrentConnectionTest.java, src/test/java/com/hubspot/imap/ImapClientAuthenticationTest.java, src/test/java/com/hubspot/imap/ImapMultiServerTest.java, src/test/java/com/hubspot/imap/MessageAddListenerTest.java, src/test/java/com/hubspot/imap/client/ImapClientTest.java, src/test/resources/profiles.yaml
This improves the test suite by not requiring the user to specify profiles to connect to actual external servers in order to run them. This also allows our tests to be run by travis.
Some tests had to be ignored to make this work because of features not yet supported in greenmail (a fix for at least one of these is being worked on in) greenmail-mail-test/greenmail#198 
I have left the multi server test profile code in place because I think it is still useful, especially for special extension like gmail. These tests simply don't run by default.
@szabowexler @cimmyv
=> Tests with greenmail

src/main/java/com/hubspot/imap/protocol/message/ImapMessage.java
The DateTimeFormatter pattern dd-MMM-yyyy, enforces the need for a date of format `03-May-2017`. Sometimes this date is set as ` 3-May-2017` (note the leading whitespace as well). This is a temporary fix to resolve smaller parsing issues. In the future, we may want to have even more flexible Date formatting. 
cc// @zklapow @szabowexler
=> Less strict date parsing

pom.xml
The new basepom requires that every dependency be in `dependencyManagement` and that no dependency in `dependencyManagement` have a specified `version` in the `dependencies` block. *phew*
See also https://github.com/HubSpot/basepom/pull/7
@zklapow 
/cc @jhaber
=> Upgrade parent to basepom 15.12

src/main/java/com/hubspot/imap/protocol/folder/FolderFlags.java, src/main/java/com/hubspot/imap/protocol/message/ImapAddress.java, src/main/java/com/hubspot/imap/protocol/message/ImapMessage.java, src/main/java/com/hubspot/imap/protocol/response/ContinuationResponse.java, src/main/java/com/hubspot/imap/protocol/response/events/ByeEvent.java, src/main/java/com/hubspot/imap/protocol/response/events/IntEvent.java, src/main/java/com/hubspot/imap/protocol/response/tagged/TaggedResponse.java
This depends on https://github.com/HubSpot/NioImapClient/pull/6 (and has a duplicate commit cause of the base branch situation). It will also make Guava ≥ 19 a requirement for this library.
@zklapow
=> Migrate some uses of Guava Objects to MoreObjects

src/main/java/com/hubspot/imap/protocol/ResponseDecoder.java
This is really dumb, if we send the same response object every time then when the next response calls `set*` on it, we will override the values in the old response. This works out fine if you read the data before sending a new command but otherwise it gets really weird.
@szabowexler @cimmyv
=> Return a new response always

src/main/java/com/hubspot/imap/ImapClientFactory.java, src/main/java/com/hubspot/imap/client/ImapClient.java, src/test/java/com/hubspot/imap/BaseGreenMailServerTest.java, src/test/java/com/hubspot/imap/ImapClientAuthenticationTest.java, src/test/java/com/hubspot/imap/ImapMultiServerTest.java
This changes the structure of the IMAP client and factory to not make the user/password built in to the client itself, but to instead be arguments to the login command itself. This also removes things like `awaitLogin` in favor of `client.login(user, pass).await()` which is more idiomatic.
This will make it easier to use the client in an un-authenticated way, or to do things before authentication, like discovering server capabilities.
This is a breaking change.
@szabowexler @cimmyv
=> Refactor login

src/main/java/com/hubspot/imap/client/ImapClient.java, src/main/java/com/hubspot/imap/protocol/exceptions/AuthenticationFailedException.java, src/main/java/com/hubspot/imap/utils/NettyCompletableFuture.java, src/test/java/com/hubspot/imap/BaseGreenMailServerTest.java, src/test/java/com/hubspot/imap/ConcurrentConnectionTest.java, src/test/java/com/hubspot/imap/ImapClientAuthenticationTest.java, src/test/java/com/hubspot/imap/ImapMultiServerTest.java, src/test/java/com/hubspot/imap/MessageAddListenerTest.java, src/test/java/com/hubspot/imap/client/ImapClientTest.java, src/test/java/com/hubspot/imap/protocol/extension/gmail/GMailFetchExtensionTest.java, src/test/java/com/hubspot/imap/protocol/extension/gmail/GMailLabelTest.java
This refactors the whole client API to use `CompletableFuture` instead of returning netty's `Future` directly. This will break basically all usages of the API, but I already bumped the version in 73886ff2a431ad9c3cefc4b8ae9b4775a692c8fd so anything still on `0.2` is safe from this change.
This also removes some of the complexities from login by removing things like `awaitLogin`. Login is now treated (mostly) like any other command.
@cimmyv @szabowexler
=> Refactor API to use CompletableFuture

src/main/java/com/hubspot/imap/protocol/ResponseDecoder.java, src/main/java/com/hubspot/imap/protocol/response/tagged/StreamingFetchResponse.java, src/test/java/com/hubspot/imap/client/ImapClientTest.java
Follow on to #10 this updates the `StreamingFetchCommand` to return `CompletableFuture` as well.
@cimmyv @szabowexler
=> Make streaming fetches use CompletableFuture

src/main/java/com/hubspot/imap/client/ImapClient.java
This adds a `shutdown` flag which replaces `closed`, all shutdown now does is prevent new writes. The connection can then be gracefully shutdown, and `closed` is only set when we actually go to close the channel itself.
@cimmyv @szabowexler
=> Improve closing connections with shutdown state

src/main/java/com/hubspot/imap/ImapClientFactory.java, src/main/java/com/hubspot/imap/client/ImapClient.java, src/main/java/com/hubspot/imap/protocol/command/ImapCommandType.java, src/main/java/com/hubspot/imap/protocol/exceptions/StartTlsFailedException.java, src/test/java/com/hubspot/imap/StartTlsTest.java
If the client factory is not using SSL/TLS this makes it possible to issue `STARTTLS` in order to upgrade the plaintext connection to a secure one.
@cimmyv
=> Add support for STARTTLS

src/main/java/com/hubspot/imap/client/ImapClient.java, src/main/java/com/hubspot/imap/protocol/response/ContinuationResponse.java, src/main/java/com/hubspot/imap/protocol/response/ImapResponse.java, src/main/java/com/hubspot/imap/protocol/response/tagged/TaggedResponse.java
This defines a single base `ImapResponse` interface and defines a new send method which expects any `ImapResponse` (either a `TaggedResponse` or `ContinuationResponse`) to prevent issues caused when a `ContinuationResponse` is returned but a `TaggedResponse` was expected.
=> Fix issues with casting ContinuationResponse to TaggedResponse

src/main/java/com/hubspot/imap/utils/parsers/string/AtomOrStringParser.java, src/test/java/com/hubspot/imap/utils/parsers/EnvelopeParseTest.java
The decoder was breaking on empty strings that were being sent as `""` as opposed to `NIL` this fixes that behavior by checking if we have already seen the first quote when we see a quote character and returning even if the size of the string is 0.
=> Handle empty quotes

src/main/java/com/hubspot/imap/protocol/ResponseDecoder.java, src/main/java/com/hubspot/imap/utils/parsers/string/BufferedBodyParser.java
@cimmyv this should cause the buffer to be correctly released when the connection is closed a prevent leaking memory.
=> Close BufferedBodyParser on channel close

pom.xml, src/main/java/com/hubspot/imap/ImapChannelInitializer.java, src/main/java/com/hubspot/imap/ImapClientFactory.java, src/main/java/com/hubspot/imap/protocol/extension/gmail/GMailLabel.java, src/test/java/com/hubspot/imap/protocol/extension/gmail/GMailFetchExtensionTest.java, src/test/java/com/hubspot/imap/protocol/extension/gmail/GMailLabelTest.java
`HostAndPost#getHost` replaced `HostAndPort#getHostText` in Guava 20 and `HostAndPort#getHostText` was removed in Guava 22. This PR should have no semantic effect on your code. [Java doc](http://google.github.io/guava/releases/21.0/api/docs/com/google/common/net/HostAndPort.html#getHostText--)
I also had to upgrade to Guava 21 as part of this (20 is the minimum required).
@zklapow
=> Use HostAndPort#getHostText instead of HostAndPort#getHost

src/main/java/com/hubspot/imap/client/ImapClient.java, src/main/java/com/hubspot/imap/protocol/command/QuotedImapCommand.java
This allows either the username or password to contain special chars (excluding double quotes) without issue.
@cimmyv
=> Quote atoms in LOGIN

src/main/java/com/hubspot/imap/ImapClientConfigurationIF.java, src/main/java/com/hubspot/imap/ImapClientFactory.java
This replaces the existing `ImapClientFactory` constructors with a `TrustManagerFactory` field in the client configuration. If a `TrustManagerFactory` is specified we build an SSL context using that factory as opposed to the default `SSLContext`. This allows for a custom `TrustManagerFactory` per-session.
@cimmyv
=> Allow custom TrustManagerFactory per connection

.travis.yml, src/main/java/com/hubspot/imap/client/ImapClient.java, src/main/java/com/hubspot/imap/protocol/ResponseDecoder.java, src/main/java/com/hubspot/imap/protocol/command/AppendCommand.java, src/main/java/com/hubspot/imap/protocol/command/ContinuableCommand.java, src/main/java/com/hubspot/imap/protocol/command/SimpleStringCommand.java, src/main/java/com/hubspot/imap/protocol/command/auth/AuthenticatePlainCommand.java, src/main/java/com/hubspot/imap/protocol/command/auth/XOAuth2Command.java, src/test/java/com/hubspot/imap/AuthenticationMechanismTest.java, src/test/java/com/hubspot/imap/BaseGreenMailServerTest.java
As the title says this PR adds support for the `PLAIN` authentication mechanism.
I reworked a bit of the `ContinuableCommand` to make this easier to implement. Will need better `CAPABILITIES` support to make this really usable though.
@cimmyv @brian5021
=> Add support for AUTHENTICATE PLAIN

src/main/java/com/hubspot/imap/ImapClientConfigurationIF.java, src/main/java/com/hubspot/imap/client/ImapClient.java, src/main/java/com/hubspot/imap/protocol/capabilities/AuthCapability.java, src/main/java/com/hubspot/imap/protocol/capabilities/AuthMechanism.java, src/main/java/com/hubspot/imap/protocol/capabilities/Capabilities.java, src/main/java/com/hubspot/imap/utils/ConfigDefaults.java, src/test/java/com/hubspot/imap/AuthenticationMechanismTest.java, src/test/java/com/hubspot/imap/BaseGreenMailServerTest.java, src/test/java/com/hubspot/imap/ImapMultiServerTest.java
This updates the login code to first send `CAPABILITY` and then choose an authentication mechanism to use based on the returned capabilities, unless a specific auth mechanism is specified.
currently only `XOAUTH2`, `PLAIN` and `LOGIN` are supported.
@cimmyv @brian5021
=> Choose preferred auth mechanism on login

src/main/java/com/hubspot/imap/protocol/ResponseDecoder.java, src/main/java/com/hubspot/imap/utils/parsers/string/BufferedBodyParser.java
Instead of parsing the ByteBuffer into a String, then recopying that String back into bytes, and then wrapping it in an InputSteam, we can instead copy the ByteBuffer once, wrap it in an input stream and pass that along to the messageBuilder where it is needed
@zklapow
=> Avoid Unnecessary Duplication

src/main/java/com/hubspot/imap/protocol/ResponseDecoder.java, src/main/java/com/hubspot/imap/utils/parsers/string/BufferedBodyParser.java
This creates a memory leak when calling the `copy` method and never releasing that new buffer
=> Revert "Avoid Unnecessary Duplication"

src/main/java/com/hubspot/imap/protocol/ResponseDecoder.java, src/main/java/com/hubspot/imap/utils/parsers/string/BufferedBodyParser.java
This should achieve the goal that https://github.com/HubSpot/NioImapClient/pull/38 was trying to accomplish.
Instead of copying the buffer into a stream or another ByteBuffer, we will copy it into a byte[]. This saves us one step of copying like #38 had but shouldn't create a memory leak
@cimmyv @zklapow
=> Copy into byte[] instead of String

src/main/java/com/hubspot/imap/utils/CRLFOutputStream.java, src/main/java/com/hubspot/imap/utils/ImapMessageWriterUtils.java, src/test/java/com/hubspot/imap/client/ImapClientTest.java
Appending messages that have isolated CR or LF is failing with servers who strictly follow RFC 2821 - 2.3.7 Lines which states:
SMTP commands and, unless altered by a service extension, message
data, are transmitted in "lines". Lines consist of zero or more data
characters terminated by the sequence ASCII character "CR" (hex value
0D) followed immediately by ASCII character "LF" (hex value 0A).
This termination sequence is denoted as in this document.
Conforming implementations MUST NOT recognize or generate any other
character or character sequence as a line terminator. Limits MAY be
imposed on line lengths by servers (see section 4.5.3).
In addition, the appearance of "bare" "CR" or "LF" characters in text
(i.e., either without the other) has a long history of causing
problems in mail …
=> Write Imap Messages to CRLF Outputstream

src/main/java/com/hubspot/imap/protocol/ResponseDecoder.java, src/main/java/com/hubspot/imap/utils/enums/EnvelopeField.java, src/main/java/com/hubspot/imap/utils/parsers/fetch/EnvelopeParser.java, src/test/java/com/hubspot/imap/utils/parsers/EnvelopeParseTest.java
In cases where we can only fetch the body and not the envelope, manually parse the headers and build the envelope.
=> If Envelope is missing but we have headers, parse them

src/main/java/com/hubspot/imap/utils/enums/EnvelopeField.java, src/main/java/com/hubspot/imap/utils/parsers/fetch/EnvelopeParser.java
There is a personal component and an email component to the email address header. This change will split the string up accordingly and set the ImapAddress correctly
@cimmyv
=> Fix parsing header addresses in EnvelopeParser

src/main/java/com/hubspot/imap/utils/parsers/fetch/EnvelopeParser.java
We were seeing cases where a header had multiple "TO" fields instead of listing them together in the field body. This joins them together to be handled like well formed headers
=> Handle when header has duplicate fields

src/main/java/com/hubspot/imap/utils/parsers/fetch/EnvelopeParser.java, src/test/java/com/hubspot/imap/utils/parsers/EnvelopeParseTest.java
We have been seeing `java.lang.IndexOutOfBoundsException: Index: 0` when calling `java.util.Collections$EmptyList.get`. This is because we do not handle NIL addresses correctly. Currently, we map NIL addresses into a `Collections.<String>emptyList();` which then gets mapped to the `Builder().parseFrom` method which assumes a non-empty list. Instead, we should just filter out NilMarkers
=> Filter out NIL addresses before mapping to ImapAddress

src/main/java/com/hubspot/imap/ImapClientFactory.java
Fixes the sslContext to use when connecting. This will allow non-default trust factories to be used when connecting.
=> Use the correct sslContext

src/main/java/com/hubspot/imap/protocol/ResponseDecoder.java
We see cases where the response code string sent to us by the server does not match any specified by https://tools.ietf.org/html/rfc3501.html#section-7.1
This will continue to throw the exception but will at least log the message that accompanied the code for the sake of debugging
=> Add logging for invalid respoonse codes to see message

src/main/java/com/hubspot/imap/protocol/message/ImapMessage.java, src/main/java/com/hubspot/imap/utils/formats/ImapDateFormat.java
This PR handles when the timezone is included in the internal date string i.e `12-Feb-2018 19:50:00 +0300 MSK` instead of `12-Feb-2018 19:50:00 +0300`. This causes our parsing to fail when using the traditional format `d-MMM-yyyy HH:mm:ss Z`.
Now we will try both formats, swallowing the exception if failure and breaking out of the loop if successful
=> Parse internal dates with zones

src/main/java/com/hubspot/imap/protocol/command/AppendCommand.java, src/main/java/com/hubspot/imap/protocol/exceptions/UnexpectedAppendResponseException.java
Previously, `APPEND COMMAND` failures on the `continueAfterResponse` threw `UnexpectedAppendResponseException` with a static message and the throwable. This is fine for exceptional failures but in the case of no throwable and that the `ImapResponse` was not an instance of `ContinuationResponse` we never exposed that response message. This change will help debug this branch of failures better
=> Log Append Command Failures Better

src/main/java/com/hubspot/imap/utils/parsers/string/AtomOrStringParser.java, src/test/java/com/hubspot/imap/utils/parsers/AtomOrStringParserTest.java
This PR adds support for imap string literal resopnses as defined in [section 4.3 of RFC 3501](https://tools.ietf.org/html/rfc3501.html#section-4.3). The section allows responses of the following format
```
* LIST (\HasNoChildren) "/" {34}
A long string literal of length 34
```
Where the `{34}` defines the length of the ensuing string literal. This allows for more arbitrary special character support.
I added two unit tests to verify that
* Properly formatted string literals are parsed properly.
* ~String literals with invalid lengths throw decoder exceptions.~
=> String Literal Support

src/main/java/com/hubspot/imap/utils/parsers/string/AtomOrStringParser.java, src/test/java/com/hubspot/imap/utils/parsers/AtomOrStringParserTest.java
This change introduced potentially undesired behavior when parsing certain response types. I'm unsure of the implications of this behavior, but I need to revert so that projects that depend on the NioImapClient can move forward without waiting on my to figure out if this change was problemativ.
Reverts HubSpot/NioImapClient#53
=> Revert "String Literal Support"

src/main/java/com/hubspot/imap/utils/parsers/fetch/EnvelopeParser.java, src/main/java/com/hubspot/imap/utils/parsers/string/AtomOrStringParser.java, src/test/java/com/hubspot/imap/utils/parsers/EnvelopeParseTest.java
Legal IMAP headers can have address lists in the form of:
`"personal <email>, personal1 <email1>, personal2 <email2>"`
`"<email>, <email1>, <email2>"`
`"email, email1, email2"`
This PR aims to handle any of these legal formats of addresses.
=> Correct Envelope Parsing From Headers

src/main/java/com/hubspot/imap/utils/parsers/string/AtomOrStringParser.java, src/test/java/com/hubspot/imap/utils/parsers/AtomOrStringParserTest.java
This PR is a revert of https://github.com/HubSpot/NioImapClient/pull/56, which is a revert of my original string literal support pr https://github.com/HubSpot/NioImapClient/pull/53.
After merging and deploying the original pr, we noticed issues with the client that were caused by issues unrelated to these changes and incorrectly concluded that it was these changes that caused the problem.
=> Revert Revert of String Literal Support

src/main/java/com/hubspot/imap/protocol/command/AppendCommand.java, src/main/java/com/hubspot/imap/utils/formats/ImapDateFormat.java
When using the APPEND command, one of the arguments is the internal date of the message we are appending. When we parse internal dates that are sent to us, we use the `d-MMM-yyyy HH:mm:ss Z` format because it will capture dates that are sent to us like "9-Apr-2018 18:08:15 +0000" as well as "09-Apr-2018 18:08:15 +0000". We did this to be as flexible as possible and give a little forgiveness to email providers who didn't correctly implement the RFC. It was incorrect to use this format for APPEND'ing messages though because email providers who are not flexible like us and are only parsing for `dd-MMM-yyyy HH:mm:ss Z` will fail to capture any date we send with a single digit day.
By making our APPENDs write out the `dd-MMM-yyyy HH:mm:ss Z` format, our command should be accepted by any RFC …
=> Use correct Date format for append

src/main/java/com/hubspot/imap/client/ImapClient.java
The goal is to detect when we have lost connection to the client earlier than we do now. We poll the inbox every 15 seconds with a NOOP command and should receive a non-exceptional OK response. If we don't receive that response, we should probably disconnect and reconnect the client. For now we will just log to make sure this accurately detects problems with a connection
=> Log when we received a non-OK NoopResponse

src/main/java/com/hubspot/imap/ImapClientFactory.java
This is an attempt to potentially close out a file descriptor leak caused by us not having a timeout on the channel for socket reads. This could result in a hanging server causing us to cancel the calling future without actually closing the resource. Trying that action over and over again could lead to tons of unclosed file descriptors.
=> Add socket timeout to Channel

pom.xml, src/main/java/com/hubspot/imap/ImapChannelInitializer.java, src/main/java/com/hubspot/imap/ImapClientConfigurationIF.java, src/main/java/com/hubspot/imap/SocksProxyConfigIF.java
The current proxy mechanism in NioImapClient is based on a non-standard "PROXY" ASCII command that is not supported in the community.  This PR adds socks proxies support.  While I could've written an integration test that used an in-memory netty-based socks proxy, I instead opted to test the whole suite of tests with a socks proxy by manually adding the socks proxy config and running a local socks proxy server via `ssh -v -C -N -D localhost:1080 localhost`.  Also, I couldn't locate any nice plug-and-play socks proxy from the java community to use in testing.
=> Add socks proxy support

pom.xml
25.8 is released now so we don't need to use a snapshot
=> Use basepom-release

pom.xml, src/test/java/com/hubspot/imap/BaseGreenMailServerTest.java, src/test/java/com/hubspot/imap/ImapMultiServerTest.java, src/test/java/com/hubspot/imap/client/ImapClientTest.java, src/test/resources/profiles.yaml
basepom 59.10 upgrades netty from 4.1.8 to 4.1.110.
this also upgrades greenmail used in tests to 1.6, and enables TLS in tests.
=> upgrade netty to 4.1.110

src/main/java/com/hubspot/imap/utils/parsers/fetch/EnvelopeParser.java, src/test/java/com/hubspot/imap/utils/parsers/EnvelopeParserTest.java
We got a lot of error like this 
```
Caused by: java.lang.IndexOutOfBoundsException: Index 9 out of bounds for length 9
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:385)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at com.hubspot.imap.utils.parsers.fetch.EnvelopeParser.parse(EnvelopeParser.java:77)
at com.hubspot.imap.protocol.ResponseDecoder.parseEnvelope(ResponseDecoder.java:580)
at com.hubspot.imap.protocol.ResponseDecoder.parseFetch(ResponseDecoder.java:328)
at …
```
=> Add log to collect info about imap envelope parsing issue

src/main/java/com/hubspot/imap/ImapClientConfigurationIF.java, src/main/java/com/hubspot/imap/ImapClientFactory.java
we've found that certain imap providers fail to connect using versions of netty > 4.1.51, which updates the default SSL protocol list. this change allows us to specify an overridden set of TLS protocols per connection.
=> allow ssl protocols to be configurable per imap connection

src/main/java/com/hubspot/imap/protocol/ResponseDecoder.java
Recently, we identified a scenario where the IMAP server for one of the ESPs (Email Service Provider) began sending a message in response to our login command. The message explained why IPs were not allowed to connect to their IMAP servers.
Response from provider: 
```
Your IP Address is blocked from further use due to AntiSpam policy. For further clarifications please contact support* BYE IMAP4rev1 Server logging out
```
In these cases, we throw an `IllegalArgumentException`, as we expect the response to adhere to [RFC3501 (login section)](https://datatracker.ietf.org/doc/html/rfc3501#section-6.2.3) response codes. 
This PR modifies this behavior so that instead of throwing an exception (which conceals the response from the IMAP server), we capture the entire response as a message and …
=> Passing illegal response from server as message
